### ISSUE TITLE
Breaking change in referenced DACPAC fails the deployment script creation

### ISSUE THREAD

**Issue by StefanOverHaevgRZ** [Herdo/SSDTLifecycleExtension#18]
**Affected version:** 1.3.1

**Description:** When trying to create the script for the attached `LibrarySystem` project, the script creation fails, saying that the column `ZipCode` cannot be found.

**Additional information:**
When consuming a shared DACPAC, e.g. referencing a column from the DACPAC in a view, this reference will be included correctly. However, when the referenced column is removed from the shared DACPAC, the product specific database project has to be updated as well. In this example, the referenced column has to be removed from the view.

However, after removing the column that doesn't exist any longer, then trying to create the deployment script, causes the following error:

```cs
ERROR: Error SQL0: The reference to external elements from the source named '[dbo].[Customer].[ZipCode]' could not be resolved, because no such source is loaded.
ERROR: Error SQL0: The reference to external elements from the source named '[dbo].[Customer].[ZipCode]' could not be resolved, because no such source is loaded.
```

Projects and structure to reproduce the issue can be found in the attached ZIP container.

**However, using the attached PowerShell script, which calls sqlpackage.exe, works perfectly fine and creates the correct deployment script.**

[DataToReproduce.zip](https://github.com/Herdo/SSDTLifecycleExtension/files/3485243/DataToReproduce.zip)

[DeploymentSkript_Generator.zip](https://github.com/Herdo/SSDTLifecycleExtension/files/3485256/DeploymentSkript_Generator.zip)

**Comment by Herdo** [comment]
The reason for this bug is that the `DacPackage` instances are loaded from a `FileStream`.
When the packages are loaded from any `Stream`, referenced DACPACs will be searched by an absolute path. This results in both the old DACPAC - which referenced the now missing column - and the new DACPAC - without the missing column - to reference the same shared DACPAC.
One expects the column, the other doesn't. This causes the error message shown the bug report.

**To solve the issue, all calls to `DacPackage.Load` have to be changed from the `Steam` overload to the `string` overload.**

In that case, when resolving references during the script generation, DacFX will use relative paths, e.g. look for the referenced DACPAC in the same directory as the DACPAC to create the script for.
This way, the old DACPAC will use the old shared DACPAC with the now missing column still there, while the new DACPAC will use the new shared DACPAC where the column is missing.

**With this, it's not possible to use any `Streams` in tests. Therefore, tests for `DacAccess` should be scrapped.**
